### PR TITLE
Some cleaning

### PR DESCRIPTION
**Pull request by michelleplur**

### CODE REVIEW

**Comment by filoozom** [comment]
Can we try to keep those files a bit clean? 😁 

```
src/pages/home-feed/pages/HomeFeed.jsx
  Line 5:10:  'Home' is defined but never used       no-unused-vars
  Line 5:21:  'AddBox' is defined but never used     no-unused-vars
  Line 5:29:  'AddCircle' is defined but never used  no-unused-vars
  Line 12:8:  'Logo' is defined but never used       no-unused-vars

src/pages/post-item/PostItemRoot.jsx
  Line 1:26:  'useEffect' is defined but never used  no-unused-vars
```

**Comment by filoozom** [comment]
Also, if we could remove the two `.mp4` files in `src/images` we might actually get this to work on the Swarm Gateway 🙂

**Comment by michelleplur** [comment]
> 

yes we did yesterday

**Comment by michelleplur** [comment]
all clean and working

**Pull request merged**
